# Generated by Django 4.0.3 on 2022-04-10 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0002_alter_barbeiro_options_alter_servico_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbeiro',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AddField(
            model_name='servico',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/imagem_servicos'),
        ),
        migrations.AddField(
            model_name='servico',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barbeiro',
            name='data_nascimento',
            field=models.DateField(blank=True, verbose_name=datetime.datetime(2022, 4, 10, 23, 27, 44, 859330)),
        ),
        migrations.AlterField(
            model_name='barbeiro',
            name='foto',
            field=models.ImageField(blank=True, upload_to='img/foto_barbeiro'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tempo',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, verbose_name=datetime.datetime(2022, 4, 10, 23, 27, 44, 859754)),
        ),
    ]
